### ISSUE TITLE
report: Related Work, sub-task 4

### ISSUE THREAD

**Issue by mewmew** [mewmew/associative_memory#14]
As this is a meta-study, the related work, or background research section will be the main content of the paper. Therefore, this section has been split into several sub-tasks, to be tracked by meeting deadlines.

For each of these sub-tasks a set of research papers (see #1) will have been read, reviewed, critically evaluated, and summarized in the report.

TODO: Add specific research papers to be read, critically evaluated and summarized by each project member for this sub-task.
- [ ] ROBIN: Arel, Itamar, Derek C. Rose, and Thomas P. Karnowski. "Deep machine learning-a new frontier in artificial intelligence research [research frontier]." Computational Intelligence Magazine, IEEE 5.4 (2010): 13-18. (issue #20)
- [ ] ROBIN: Barto, Andrew G., Richard S. Sutton, and Peter S. Brouwer. "Associative search network: A reinforcement learning associative memory." Biological cybernetics 40.3 (1981): 201-211. (issue #19)
- [ ] ROBIN: Palm, Günther. "On associative memory." Biological cybernetics 36.1 (1980): 19-31. (issue #21)

**Comment by mewmew** [comment]
See https://github.com/mewmew/associative_memory/issues/11#issuecomment-222318504
